name: blue_suv_grass
source_path: ./assets/${cam_path} 
model_path: ./assets/${cam_path}
target_splat : "adv_blue_suv_grass.ply"
background_splat : "nyc_block_cycles_shadow.ply"
cam_indices: [0]
is_targeted: False
target: 'potted_plant'
untarget: 'car'
detector_name: detectron2 #yolov3 #yolov8 
