name: gray_car
source_path: ./assets/${cam_path} 
model_path: ./assets/${cam_path}
target_splat : ./${splat_asset_path}/nyc_gray_car.ply
background_splat : ./${splat_asset_path}/nyc_block_cycles_shadow.ply
combine_splats_paths = [target_splat, background_splat]
cam_indices: [0]
is_targeted: False
target: 'train'
untarget: 'car'
detector_name: detectron2 #yolov3 #yolov8 
