name: maserati
source_path: "assets/nyc_block"
model_path: "asesets/nyc_block"
combine_splats_paths: ["output/nyc_maserati.ply", "output/nyc_block_cycles_shadow.ply"]
cam_indices: [24]
target: 'truck'
untarget: null
detector_name: yolov3 #yolov8 #detectron2
