defaults:
  - scene: maserati
  - _self_

cam_path: "nyc_block"
splat_asset_path: "output"
data_device: "cuda"
device: "7"
eval: false
images: "images"
n_views: 100
num_classes: 256
object_path: "object_mask"
random_init: false
resolution: 1
sh_degree: 3
train_split: false
white_background: false
no_groups: true
combine_splats: true
write_images: false

# Optimization parameters
densification_interval: 100
density_From_iter: 500
densify_grad_threshold: 0.0002
density_until_iter: 15000
feature_lr: 0.0025
iterations: 30000
lambda_dssim: 0.2
opacity_lr: 0.05
opacity_reset_interval: 3000
percent_dense: 0.01
position_lr_delay_mult: 0.01
position_lr_final: 1.6e-6
position_lr_init: 0.00016
position_lr_max_steps: 30000
reg3d_interval: 2
reg3d_k: 5
reg3d_lambda_val: 2
reg3d_max_points: 300000
reg3d_sample_size: 1000
rotation_lr: 0.001
scaling_lr: 0.005

# Attack options
epsilon: 5.0
alpha: 0.5
selected_obj_ids: [117]     # example list
shuffle_cams: false
start_cam: 0
end_cam: 1
add_cams: 1
shift_amount: 0.15
attack_conf_thresh: 0.25
batch_mode: false
batch_size: 5
max_iters: 100

# Additional debug flags
compute_cov3D_python: false
convert_SHs_python: false
debug: false

sysconfig:
  output_path: results/${scene.name}
  #log_dir: ./results/${scene.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  log_dir: ./results/${scene.name}/${now:%Y-%m-%d}/${cam_path}_${scene.target_splat}_${scene.detector_name}_${now:%H-%M}

hydra:
  run:
    # dir: ./results/${scene.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}  
    dir: ./results/${scene.name}/${now:%Y-%m-%d}/${cam_path}_${scene.target_splat}_${scene.detector_name}_${now:%H-%M}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${cam_path}_${scene.target_splat}_${scene.detector_name}
