# conf/attack.yaml

data_device: "cuda"
device: "7"
eval: false
images: "images"
model_path: "/raid/mhull32/gaussian-splatting/output/nyc_block"
n_views: 100
num_classes: 256
object_path: "object_mask"
random_init: false
resolution: 1
sh_degree: 3
source_path: "/raid/mhull32/gaussian-splatting/output/nyc_block"
train_split: false
white_background: false
no_groups: false
combine_splats: true

# Optimization parameters
densification_interval: 100
density_From_iter: 500
densify_grad_threshold: 0.0002
density_until_iter: 15000
feature_lr: 0.0025
iterations: 30000
lambda_dssim: 0.2
opacity_lr: 0.05
opacity_reset_interval: 3000
percent_dense: 0.01
position_lr_delay_mult: 0.01
position_lr_final: 1.6e-6
position_lr_init: 0.00016
position_lr_max_steps: 30000
reg3d_interval: 2
reg3d_k: 5
reg3d_lambda_val: 2
reg3d_max_points: 300000
reg3d_sample_size: 1000
rotation_lr: 0.001
scaling_lr: 0.005

# Attack options
epsilon: 5.0
alpha: 0.5
combine_splats_paths: ["output/nyc_block/nyc_maserati.ply", "output/nyc_block/nyc_block_cycles_shadow.ply"]
selected_obj_ids: [117]     # example list
target: [0]               # person (see classes.txt)
untarget: null
start_cam: 0
end_cam: 1
add_cams: 1
shift_amount: 0.15
attack_conf_thresh: 0.7
batch_mode: false
cam_indices: [0]

# Additional debug flags
compute_cov3D_python: false
convert_SHs_python: false
debug: false
